version: 2
workflows:
  version: 2
  test:
    jobs:
      - ruby-2.5
      - ruby-2.6
      - ruby-2.7
jobs:
  ruby-2.7: &default-build
    docker:
      - image: circleci/ruby:2.7
        environment:
          BUNDLE_PATH: vendor/bundle
          CODECOV_ENABLED: true
    steps:
      - checkout

      - run:
          name: Install latest system gems
          command: sudo gem update --system

      - run:
          name: Install latest bundler
          command: gem install bundler

      - run:
          name: Bundler version
          command: bundle -v

      - run:
          name: Install SQLite 3
          command: sudo apt update && sudo apt install -y sqlite3

      # Restore bundle cache
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
            - gems-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run RSpec
          command: bundle exec rspec --force-color --format doc --format RspecJunitFormatter --out ./spec/test_results/results.xml

      - store_test_results:
          path: spec/test_results

      - run:
          name: Run Rubocop
          command: bundle exec rubocop
  ruby-2.5:
    <<: *default-build
    docker:
      - image: circleci/ruby:2.5
  ruby-2.6:
    <<: *default-build
    docker:
      - image: circleci/ruby:2.6
